Гридин Андрей
urfu-2018/markup-task-6 pull request #1
Opened 2018-11-10 03:52 UTC by Drusalyator

Не уверен в полной правильности работы медиа запросов (в браузере работает). Вроде на паре говорили, что надо что-то еще прикручивать к медиа. Как лекцию выложат, если что-то не так - исправлю

2018-11-10 03:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 04:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 10:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 10:46 UTC, Drusalyator commented
Вроде как исправил работу media для разных устройств. Немного отошел от задание, т.к. при ширине от 375 до 730 не работало на iphone se и honor 10 (у них viewport меньше). Поставил от 300 до 730. Если это критично, то верну на место

2018-12-08 08:42 UTC, trixartem commented
Включить фильтры и в строке остается меньше 2-х карточек - они выравниваются по центру, а надо что бы они приливали к левому краю. Что бы соблюдалась сетка из карточек.

2018-12-10 18:31 UTC, trixartem requested changes
по верстке все ок, но есть пара комментов

2018-12-10 18:31 UTC, trixartem commented on index.html
> +                <div class="label-caption">Категория</div>
Похоже на список

2018-12-10 18:31 UTC, trixartem commented on index.html
> +                    <p class="cat-age">Возраст: ~ 1.5 года</p>
Похоже на список

2018-12-10 18:31 UTC, trixartem commented on index.html
> +        <footer class="site-footer">
Сделай так, что бы футер был прибит к нижней части страницы, если контента мало.

2018-12-10 19:38 UTC, Drusalyator commented on index.html
> +        <footer class="site-footer">
Так ведь и в моем варианте так и есть, или я что-то не понимаю? Получается что у главной части задана min-height: calc(100vh - 160px), чтоб футер как раз прибивался в низ

2018-12-15 16:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 16:30 UTC, Drusalyator commented
Исправил замечания, плюс постарался сделать подобие бэма, а также сделал отключение фильтром при уменьшении экрана

2018-12-18 13:33 UTC, trixartem commented
👍

2018-12-18 13:33 UTC, closed without merging