initial
urfu-2018/markup-task-6 pull request #11
Opened 2018-11-14 05:29 UTC by KatySolo

2018-11-14 05:29 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-24 08:49 UTC, chrighter requested changes
🍅

2018-11-24 08:49 UTC, chrighter commented on index.css
> +    background: white;
![image](https://user-images.githubusercontent.com/22082557/48966137-f5cd6880-efec-11e8-8a1c-84a82f990db0.png)

2018-11-24 08:49 UTC, chrighter commented on index.css
> +.catFilter > div
Класс нигде не используется

2018-11-24 08:49 UTC, chrighter commented on index.css
> +@media screen and (min-width: 375px) and (max-width: 730px)
👍

2018-11-24 08:49 UTC, chrighter commented on index.css
> +
Лишняя строка

2018-11-24 08:49 UTC, chrighter commented on index.css
> +    .breed-radio[value='british']:checked ~ .cards .british .card-layout,
Давай попробуем объединить стили

2018-11-24 08:49 UTC, chrighter commented on index.html
> +                <img src="mail.png" class="mail-icon" alt="mail">
Что-то с отступами

2018-11-24 08:49 UTC, chrighter commented on index.html
> +                    <br>
Двойной `<br>` используется только для отступа, то есть как стилевой элемент
Можно создать дополнительные классы и сделать то же самое с помощью `margin/padding`

2018-11-24 08:49 UTC, chrighter commented on index.html
> +    <input type="radio" class="breed-radio" id="british" value="british" name="breedRadio">
У тебя сейчас переключение происходит только по нажатию на текст
Давай сделаем так, что переключение будет работать, даже если нажимать не только на текст, а в любое место кнопки

![image](https://user-images.githubusercontent.com/22082557/48966235-27dfca00-efef-11e8-920d-27496c0b8a3e.png)

2018-11-25 12:24 UTC, KatySolo commented on index.css
> +    .breed-radio[value='british']:checked ~ .cards .british .card-layout,
я не очень поняла что с чем объединить 🙄

2018-11-25 12:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-28 08:38 UTC, chrighter approved these changes

2018-12-28 08:38 UTC, closed without merging