Done
urfu-2018/markup-task-6 pull request #17
Opened 2018-11-14 15:42 UTC by IIaKyJIuH

2018-11-14 15:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 06:29 UTC, mokhov commented
Почти всё ок, но футер хорошо бы как в прошлой задаче прибивать к низу страницы, когда по вертикали мало карточек

2018-11-19 06:29 UTC, mokhov commented
🍅

2018-11-19 08:29 UTC, mokhov requested changes
🍅

2018-11-20 11:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-20 11:31 UTC, IIaKyJIuH commented
(Футер теперь имеет "position: fixed")*

2018-12-15 08:45 UTC, mokhov commented
position: fixed – это чит. В прошлых лекциях было достаточно информации, чтобы реализовать нужное поведение без position: fixed
🍅

2019-01-11 09:26 UTC, closed without merging