v1
urfu-2018/markup-task-6 pull request #27
Opened 2018-11-14 19:44 UTC by JudithRomero

2018-11-14 19:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-15 09:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-23 09:02 UTC, Dotokoto commented
В firefox на десктопе появляется лишний скролл на блоке с котиками

2018-11-23 09:07 UTC, Dotokoto commented
Еще тени на карточках обрезаются сверху, слева и справа на верхних/левых/правых карточках, выглядит не очень красиво, хорошо бы поправить

2018-11-23 09:10 UTC, Dotokoto commented
<img width="1253" alt="2018-11-23 14-09-20" src="https://user-images.githubusercontent.com/8973726/48935410-6e6af100-ef29-11e8-9570-67dec24898c3.png">
При изменении высоты браузера футер начинает наезжать на контент

2018-11-23 09:12 UTC, Dotokoto commented
<img width="1133" alt="2018-11-23 14-11-58" src="https://user-images.githubusercontent.com/8973726/48935512-c30e6c00-ef29-11e8-8250-73ea8289cb1f.png">
На планшетном размере при маленьком экране карточки наехали друг на друга

2018-11-23 09:28 UTC, dotokoto requested changes

2018-11-23 09:28 UTC, dotokoto commented on desktop.css
> +    grid-gap: 20px;  */
Комменты лучше удалять, если они не нужны

2018-11-23 09:28 UTC, dotokoto commented on index.html
> +                        <div class="entry-title">Ася</div>
Это заголовок карточки, можно выбрать более семантичный тег

2018-11-25 06:30 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 06:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 06:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 06:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-27 06:26 UTC, dotokoto commented
Принято 👍

2018-11-27 06:26 UTC, closed without merging