Решение
urfu-2018/markup-task-6 pull request #31
Opened 2018-11-14 20:47 UTC by creewick

http://creewick.github.io/markup-task-6

2018-11-14 20:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 19:47 UTC, SemyonMakhaev requested changes
🍅 

1. А тень при наведении на карточку, как на макете?
2. Будет очень круто, если сможешь приблизить фильтр по возрасту к макету

2018-11-19 19:47 UTC, SemyonMakhaev commented on index.css
> +    background-color: rgb(250, 250, 250);
Функцию `rgb` здесь использовать избыточно, потому что ты ничего не вычисляешь. Используй `hex`

2018-11-26 19:36 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-26 19:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-06 16:53 UTC, SemyonMakhaev reviewed
Фильтр у меня (Yandex Browser 18) выглядит не как на макете, можно лучше:

![2018-12-06 21-48-33](https://user-images.githubusercontent.com/18099714/49598685-fd9fec00-f9a0-11e8-9c9d-aec7c30dcb30.png)

Вот статья про стилизацию таких контролов, там указаны основные псевдоэлементы: http://brennaobrien.com/blog/2014/05/style-input-type-range-in-every-browser.html. Попробуй с ними поэкспериментировать.

В остальном всё супер, молодец! 👍

2018-12-08 18:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-09 03:31 UTC, SemyonMakhaev approved these changes
🍏 

Даже в firefox работает! 🎉 🎉 🎉

2018-12-09 03:31 UTC, SemyonMakhaev commented on index.css
> +.range::-moz-range-thumb
Селекторы [234](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R234) и [247](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R247) совпадают с точностью до правила `-webkit-appearance: none`. Их можно сгруппировать

2018-12-09 03:31 UTC, SemyonMakhaev commented on index.css
> +    background: transparent;
`background-color`

```suggestion
    background-color: transparent;
```

Аналогично: [253](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R253), [261](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R261), [267](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R267), [274](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R274), [281](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R281), [288](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R288), [304](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R304), [312](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R312), [318](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R318), [323](https://github.com/urfu-2018/markup-task-6/pull/31/commits/bf6b71d941fb0b44a8c54522306406206748f516#diff-bca1542f88ef8253c16b452e9ad09f98R323). Надо за этим следить

2018-12-09 03:32 UTC, closed without merging