Анисимов Данил
urfu-2018/markup-task-6 pull request #56
Opened 2018-11-15 11:24 UTC by frosthamster

[Посмотреть решение](https://hruview.herokuapp.com/frosthamster/markup-task-6/master/index.html)

2018-11-15 11:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-20 19:36 UTC, SemyonMakhaev requested changes
🍅 

1. Давай попробуем фильтр сверстать, а не вставить картинкой

2. На узких экранах картинки сжимаются. Следует сохранять пропорции изображения при ресайзе
![2018-11-21 00-32-04](https://user-images.githubusercontent.com/18099714/48797947-53c82a80-ed25-11e8-9e08-a890c117aff1.png)

2018-11-22 08:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-22 08:41 UTC, frosthamster commented
под webkit фильтр сверстался нормально, но на мозиле почему то не получается вытащить thumb на передний план

даже прописывая стили в ::-moz-range-thumb

2018-11-26 10:58 UTC, SemyonMakhaev commented
> под webkit фильтр сверстался нормально, но на мозиле почему то не получается вытащить thumb на передний план
> 
> даже прописывая стили в ::-moz-range-thumb

А через `-moz-range-track` не получится хакнуть? Задать ему `z-index` поменьше, например

2018-11-26 10:59 UTC, SemyonMakhaev approved these changes
🍏

2018-11-26 11:28 UTC, frosthamster commented
Хрюндель сломался?

2018-11-26 11:31 UTC, SemyonMakhaev commented
>Хрюндель сломался?

Нет, он поставит лейблы, когда я закрою пулл 😅 
Я просто подумал, что ты сначала поэкспериментируешь `-moz-range-track`, а потом я закрою. В остальном мне всё понравилось по коду и реализации

2018-11-26 13:02 UTC, frosthamster commented
аа, а то я яблоко увидел просто
хорошо, сейчас попробую через -moz-range-track сделать

2018-11-26 17:10 UTC, frosthamster commented
не получается

даже если задать явно
.date_picker::-moz-range-track
{
    z-index: -1;
}

.date_picker::-moz-range-thumb
{
    z-index: 1;
}

2018-12-06 16:32 UTC, SemyonMakhaev commented
> не получается
> 
> даже если задать явно
> .date_picker::-moz-range-track
> {
> z-index: -1;
> }
> 
> .date_picker::-moz-range-thumb
> {
> z-index: 1;
> }

Да, у меня что-то тоже не получается (
Странно, в ff эти псевдоэлементы должны норм работать...

Ну ладно, абсолютной кроссбраузерности в задаче не требуется, так что ок

2018-12-06 16:33 UTC, closed without merging