Кузовлева Мария
urfu-2018/markup-task-6 pull request #59
Opened 2018-11-15 11:49 UTC by jellymary

2018-11-15 11:49 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-15 11:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 08:40 UTC, mokhov requested changes
1. Футер должен висеть внизу как и в прошлом задании
2. Нужно немного поправить выбор возраста
В остальном круто, но пока 🍅

2018-11-19 08:40 UTC, mokhov commented on index.html
> +            <input id="age-slider" type="range" min="0.5" max="5" step="0.5" value="1.5">
Слайдер с двумя значениями у нас на картинке

2018-11-21 14:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-21 14:37 UTC, jellymary commented on index.html
> +            <input id="age-slider" type="range" min="0.5" max="5" step="0.5" value="1.5">
я не знаю, как сделать рабочий слайдер с двумя бегунками, поэтому я его просто сверстала из div'ов как на картике

2018-12-15 08:43 UTC, mokhov commented
Отлично

2018-12-15 08:43 UTC, closed without merging