Наумов Егор
urfu-2018/markup-task-6 pull request #63
Opened 2018-11-15 12:08 UTC by EgorNmv

2018-11-15 12:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-15 18:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-15 18:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 08:42 UTC, mokhov requested changes
1. Если ресайзить, то можно увидеть такое
https://screenshots.firefox.com/ZeDi9K3ovJC9hb2p/hruview.herokuapp.com

Не нужно изменять пропорции картинок

2. Выбор возраста состоит из двух параметров

2018-11-19 08:42 UTC, mokhov commented on index.css
> +footer .ooo
Плохое название класса

2018-11-21 12:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 08:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:42 UTC, mokhov commented
Не исправлено:
> Не нужно изменять пропорции картинок

🍅

2018-12-20 19:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2019-01-11 09:22 UTC, mokhov commented
<img width="428" alt="screenshot 2019-01-11 at 12 21 47" src="https://user-images.githubusercontent.com/357689/51024784-8959f900-159b-11e9-9a59-796301136c32.png">
Реальные пропорции картинки иные. Принимаю на полбалла

2019-01-11 09:22 UTC, closed without merging